### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by JuhahuJ** [kluopaja/ot-harjoitustyo#1]
Ladattu 4.5 n. klo 22
Peli näyttää hyvältä. Peli toimi koneellani ja vaikutti toimivan oikein.

Mielestäni kehittää voisi:
-Readme:ssä voisi selittää pelin tarkoituksen paremmin.
-Lentokone kuvan voisi peilata, kun sen suuntaa vasemmalle.
-python tiedostot voisi mahdollisesti jaoitella kansioihin, jotta eri osien löytäminen olisi helpompaa

Muuten peli ja sen sisältämä koodi näyttää yleisesti hyvältä muutamia koodista pylintin kanssa löytyviä ongelmia lukuunottamatta

**Comment by kluopaja** [comment]
Kiitos kommenteista.
